-- 제목으로 검색

SELECT BOARD_TITLE, BOARD_NO
  FROM KH_BOARD
 WHERE
       BOARD_TITLE LIKE '%' || '테' || '%';

SELECT BOARD_TITLE, BOARD_NO
  FROM KH_BOARD
 WHERE
       BOARD_CONTENT LIKE '%' || '다' || '%';

SELECT BOARD_TITLE, BOARD_NO
  FROM KH_BOARD
  JOIN KH_MEMBER ON (BOARD_WRITER = USER_NO)
 WHERE
       USER_NAME LIKE '%' || '홍' || '%';