CREATE TABLE MP_MEMBER(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(30) UNIQUE NOT NULL,
	USER_PWD VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N'))
);

CREATE SEQUENCE MP_UNO
	   NOCACHE;

INSERT INTO MP_MEMBER(USER_NO, USER_ID, USER_PWD, USER_NAME, EMAIL) VALUES
(MP_UNO.NEXTVAL, 'admin', '1234', '홍길동', 'hong@kh.com');

COMMIT;

SELECT * FROM MP_MEMBER;